// Code generated by marko-go. DO NOT EDIT.
package widgets

import "github.com/svallory/go-marko/runtime"

type PanelInput struct {
	Attrs   map[string]any
	Content runtime.Body
}

// Panel renders the panel.marko template into w.
func Panel(w *runtime.Writer, input PanelInput) {
	w.HTML("<div")
	w.HTML(runtime.Attrs(runtime.A{Name: "class", Value: "panel"}, input.Attrs))
	w.HTML(">")
	if input.Content != nil {
		input.Content(w)
	}
	w.HTML("</div>")
}
