/**
 * Go source assembly: indentation, the gofmt-alignment emulation, the import
 * block, and the generated file's skeleton.
 *
 * Everything here is string-level -- no AST, no Marko knowledge. That is the
 * point of the split: the resume translators (resume.mjs) emit statement
 * STRINGS and this module decides where in the file they land, without either
 * side knowing the other's internals.
 */

import { renderInputStruct } from "./inputstruct.mjs";
import { goStringLiteral } from "./names.mjs";
import { dropUnusedScopeVars } from "./resume.mjs";

/** Prefix every line of every entry with one tab, preserving blank lines. */
export function indent(lines) {
  return lines
    .map((l) => l.split("\n").map((ln) => (ln === "" ? "" : "\t" + ln)).join("\n"))
    .join("\n");
}

/**
 * Build the file's import block.
 *
 * Lists the runtime plus one aliased import per cross-directory dependency
 * actually used: the globals package (when this template reads `$global` and
 * the Globals struct lives elsewhere) and every custom tag package.
 *
 * @returns {{block: string, paths: string[]}} the rendered `import ...` and
 *   the set of import paths, in the order they were added.
 */
export function buildImportBlock(ctx) {
  const importLines = ['"github.com/svallory/go-marko/runtime"'];
  const seenPaths = new Set();

  // The globals package, when this template reads `$global` and the Globals
  // struct lives in another package. Same alias table as tag imports, so a
  // collision was already resolved when the alias was handed out.
  const globalsEntry = ctx.globalsEntry;
  if (globalsEntry && !globalsEntry.sameDir) {
    seenPaths.add(globalsEntry.goImportPath);
    importLines.push(
      globalsEntry.alias !== globalsEntry.pkgName
        ? `${globalsEntry.alias} "${globalsEntry.goImportPath}"`
        : `"${globalsEntry.goImportPath}"`,
    );
  }

  for (const entry of [...ctx.usedTags].sort((a, b) =>
    a.goImportPath.localeCompare(b.goImportPath),
  )) {
    if (entry.sameDir || seenPaths.has(entry.goImportPath)) continue;
    seenPaths.add(entry.goImportPath);
    const needsAlias = entry.alias !== entry.pkgName;
    importLines.push(
      needsAlias
        ? `${entry.alias} "${entry.goImportPath}"`
        : `"${entry.goImportPath}"`,
    );
  }

  const block =
    importLines.length === 1
      ? `import ${importLines[0]}`
      : `import (\n${importLines.map((l) => "\t" + l).join("\n")}\n)`;
  return { block, paths: [...seenPaths] };
}

/**
 * Assemble the whole generated file from the translated pieces.
 *
 * @param {object} ctx
 * @param {object} pieces
 * @param {string[]} pieces.moduleConstDecls package-level `var` declarations
 * @param {string[]} pieces.bodyGo            renderer body statements
 * @returns {{code: string, imports: string[]}}
 */
export function assembleFile(ctx, { moduleConstDecls, bodyGo }) {
  const { block: importBlock, paths } = buildImportBlock(ctx);

  const parts = [
    "// Code generated by marko-go. DO NOT EDIT.",
    `package ${ctx.goPackage}`,
    "",
    importBlock,
    "",
  ];
  if (moduleConstDecls.length > 0) {
    // `static const` in Marko is module-scoped and evaluated once. Go
    // package vars are the closest equivalent (a Go `const` can't hold a
    // composite literal).
    parts.push(moduleConstDecls.join("\n\n"), "");
  }
  parts.push(renderInputStruct(ctx.structName, ctx.inputFields), "");
  // Structs generated for inline object types in `interface Input`, named
  // <OuterStruct><Field> (CounterInput.events -> CounterInputEvents). Emitted
  // after the Input struct that references them, in declaration order.
  for (const s of ctx.nestedStructs) {
    parts.push(renderInputStruct(s.name, s.fields), "");
  }
  // FR12. Every render function is bracketed by BeginTemplate/EndTemplate,
  // not just the ones that emit resume state. The pair maintains the Writer's
  // render DEPTH, and depth is what decides which render flushes the resume
  // payload -- so a tag that contributes nothing itself still has to be
  // counted, or a page calling it would flush too early. See
  // runtime.Writer.BeginTemplate.
  parts.push(
    `// ${ctx.pascalName} renders the ${ctx.templateName}.marko template into w.`,
    `func ${ctx.pascalName}(w *runtime.Writer, input ${ctx.structName}) {`,
    indent([
      "w.BeginTemplate()",
      // FR12. A PAGE with client code names its bundle here; the Writer emits
      // the module script after the resume payload, because init() needs
      // M._.r to exist. Declared at the TOP so it survives an early return
      // once the renderer grows any.
      ...(ctx.resume.clientBundleURL
        ? [`w.ClientBundle(${goStringLiteral(ctx.resume.clientBundleURL)})`]
        : []),
      ...dropUnusedScopeVars(ctx, bodyGo),
      `w.EndTemplate(${goStringLiteral(`${ctx.templateName}.marko`)})`,
    ]),
    "}",
    "",
  );

  return { code: alignKeyValueRuns(parts.join("\n")), imports: paths };
}

/**
 * gofmt aligns the values of consecutive single-line `Key: value,` entries
 * inside a composite literal (and `Name Type` inside a struct type). We emit
 * gofmt-clean Go directly rather than shelling out to the Go toolchain, so
 * this reproduces that one rule: within each maximal run of same-indent
 * lines matching `key: value,` -- broken by any other line, including a
 * multi-line value's opening brace -- pad the key column to the widest key.
 *
 * gofmt also breaks a run when a line is "too far" from its neighbours, but
 * that threshold only applies to comment alignment, not composite literals.
 */
export function alignKeyValueRuns(code) {
  const lines = code.split("\n");
  // Key is a bare Go identifier or a simple quoted string; the entry must
  // end in a comma. That's narrow enough that a `w.HTML("http://...")` line
  // (which also contains a colon) can never be mistaken for a literal entry.
  const KV = /^(\t*)([A-Za-z_][A-Za-z0-9_]*|"[^"\\]*"): (\S.*?)(,)$/;
  let i = 0;
  while (i < lines.length) {
    const m = KV.exec(lines[i]);
    // A value ending in `{` opens a multi-line literal; gofmt treats such a
    // line as breaking the run rather than joining it.
    if (!m || m[3].endsWith("{")) {
      i++;
      continue;
    }
    const indentStr = m[1];
    const run = [];
    let j = i;
    for (; j < lines.length; j++) {
      const mm = KV.exec(lines[j]);
      if (!mm || mm[1] !== indentStr || mm[3].endsWith("{")) break;
      run.push(mm);
    }
    if (run.length > 1) {
      const width = Math.max(...run.map((r) => r[2].length));
      run.forEach((r, k) => {
        lines[i + k] = `${r[1]}${r[2]}:${" ".repeat(width - r[2].length + 1)}${r[3]}${r[4]}`;
      });
    }
    i = j > i ? j : i + 1;
  }
  return lines.join("\n");
}
