// Code generated by marko-go. DO NOT EDIT.
package pages

import "github.com/svallory/go-marko/runtime"

// GeneratedByMarkoGo_v0_1 asserts this file was generated by a marko-go whose
// minor version matches the runtime package below. A build error here
// ("undefined: runtime.GeneratedByMarkoGo_v0_1") means codegen and runtime have drifted -- update whichever is
// behind so both are on the same major.minor version.
var _ = runtime.GeneratedByMarkoGo_v0_1

type AttrClassArrayInput struct {
	Active bool
}

// AttrClassArray renders the attr-class-array.marko template into w.
func AttrClassArray(w *runtime.Writer, input AttrClassArrayInput) {
	w.BeginTemplate()
	w.AllocScopeID()
	w.HTML("<div")
	w.HTML(runtime.AttrClass([]any{"row", runtime.And(input.Active, "row-active")}))
	w.HTML(">content</div>")
	w.EndTemplate("attr-class-array.marko")
}
