// Code generated by marko-go. DO NOT EDIT.
package pages

import "github.com/svallory/go-marko/runtime"

type AttrClassArrayInput struct {
	Active bool
}

// AttrClassArray renders the attr-class-array.marko template into w.
func AttrClassArray(w *runtime.Writer, input AttrClassArrayInput) {
	w.HTML("<div")
	w.HTML(runtime.AttrClass([]any{"row", runtime.And(input.Active, "row-active")}))
	w.HTML(">content</div>")
}
