// Code generated by marko-go. DO NOT EDIT.
package pages

import (
	"github.com/svallory/go-marko/runtime"
	"goldenfix/ui/tags/widgets/nested"
)

type CrossDirInput struct{}

// CrossDir renders the cross-dir.marko template into w.
func CrossDir(w *runtime.Writer, input CrossDirInput) {
	w.BeginTemplate()
	w.AllocScopeID()
	w.HTML("<div>")
	nested.InnerBadge(w, nested.InnerBadgeInput{
		Text: "deep",
	})
	w.HTML("</div>")
	w.EndTemplate("cross-dir.marko")
}
