// Code generated by marko-go. DO NOT EDIT.
package pages

import "github.com/svallory/go-marko/runtime"

// GeneratedByMarkoGo_v0_1 asserts this file was generated by a marko-go whose
// minor version matches the runtime package below. A build error here
// ("undefined: runtime.GeneratedByMarkoGo_v0_1") means codegen and runtime have drifted -- update whichever is
// behind so both are on the same major.minor version.
var _ = runtime.GeneratedByMarkoGo_v0_1

type ForLoopInput struct {
	Items []string
}

// ForLoop renders the for-loop.marko template into w.
func ForLoop(w *runtime.Writer, input ForLoopInput) {
	w.BeginTemplate()
	w.AllocScopeID()
	w.HTML("<ul>")
	runtime.ForOfIndexed(input.Items, func(item string, i int) {
		w.AllocScopeID()
		w.HTML("<li>")
		w.HTML(runtime.Escape(i))
		w.HTML(": ")
		w.HTML(runtime.Escape(item))
		w.HTML("</li>")
	})
	w.HTML("</ul>")
	w.EndTemplate("for-loop.marko")
}
