// Code generated by marko-go. DO NOT EDIT.
package pages

import (
	"github.com/svallory/go-marko/runtime"
	"goldenfix/ui"
)

type GlobalReadInput struct{}

// GlobalRead renders the global-read.marko template into w.
func GlobalRead(w *runtime.Writer, input GlobalReadInput) {
	markoGlobal, _ := w.Globals().(ui.Globals)
	w.HTML("<div>Current path: ")
	w.HTML(runtime.Escape(markoGlobal.Path))
	w.HTML("</div>")
}
