// Code generated by marko-go. DO NOT EDIT.
package pages

import "github.com/svallory/go-marko/runtime"

type HtmlScriptInput struct{}

// HtmlScript renders the html-script.marko template into w.
func HtmlScript(w *runtime.Writer, input HtmlScriptInput) {
	w.BeginTemplate()
	w.AllocScopeID()
	w.HTML("<div><script")
	w.HTML(" src=/assets/js/app.js defer></script></div>")
	w.EndTemplate("html-script.marko")
}
