// Code generated by marko-go. DO NOT EDIT.
package pages

import "github.com/svallory/go-marko/runtime"

type IfElseInput struct {
	LoggedIn bool
}

// IfElse renders the if-else.marko template into w.
func IfElse(w *runtime.Writer, input IfElseInput) {
	if runtime.Truthy(input.LoggedIn) {
		w.HTML("<p>Welcome back.</p>")
	} else {
		w.HTML("<p>Please log in.</p>")
	}
}
