// Code generated by marko-go. DO NOT EDIT.
package pages

import "github.com/svallory/go-marko/runtime"

// GeneratedByMarkoGo_v0_1 asserts this file was generated by a marko-go whose
// minor version matches the runtime package below. A build error here
// ("undefined: runtime.GeneratedByMarkoGo_v0_1") means codegen and runtime have drifted -- update whichever is
// behind so both are on the same major.minor version.
var _ = runtime.GeneratedByMarkoGo_v0_1

type IfElseInput struct {
	LoggedIn bool
}

// IfElse renders the if-else.marko template into w.
func IfElse(w *runtime.Writer, input IfElseInput) {
	w.BeginTemplate()
	w.AllocScopeID()
	if runtime.Truthy(input.LoggedIn) {
		w.AllocScopeID()
		w.HTML("<p>Welcome back.</p>")
	} else {
		w.AllocScopeID()
		w.HTML("<p>Please log in.</p>")
	}
	w.EndTemplate("if-else.marko")
}
