// Code generated by marko-go. DO NOT EDIT.
package pages

import "github.com/svallory/go-marko/runtime"

type InterpolateInput struct {
	Name string
}

// Interpolate renders the interpolate.marko template into w.
func Interpolate(w *runtime.Writer, input InterpolateInput) {
	w.BeginTemplate()
	w.AllocScopeID()
	w.HTML("<div>Hello, ")
	w.HTML(runtime.Escape(input.Name))
	w.HTML("!</div>")
	w.EndTemplate("interpolate.marko")
}
