// Code generated by marko-go. DO NOT EDIT.
package pages

import "github.com/svallory/go-marko/runtime"

var moduleConstVariants = map[string]string{
	"default": "btn-default",
	"outline": "btn-outline",
}

type ModuleConstInput struct {
	Variant string
}

// ModuleConst renders the module-const.marko template into w.
func ModuleConst(w *runtime.Writer, input ModuleConstInput) {
	w.HTML("<button")
	w.HTML(runtime.AttrClass(moduleConstVariants[input.Variant]))
	w.HTML(">Click</button>")
}
