// Code generated by marko-go. DO NOT EDIT.
package pages

import "github.com/svallory/go-marko/runtime"

type NestedInputInput struct {
	User NestedInputInputUser
}

type NestedInputInputUser struct {
	Name string
	Age  float64
}

// NestedInput renders the nested-input.marko template into w.
func NestedInput(w *runtime.Writer, input NestedInputInput) {
	w.BeginTemplate()
	w.AllocScopeID()
	w.HTML("<div>")
	w.HTML(runtime.Escape(input.User.Name))
	w.HTML(" is ")
	w.HTML(runtime.Escape(input.User.Age))
	w.HTML(" years old.</div>")
	w.EndTemplate("nested-input.marko")
}
