// Code generated by marko-go. DO NOT EDIT.
package pages

import "github.com/svallory/go-marko/runtime"

type NullishFallbackInput struct {
	Title string
}

// NullishFallback renders the nullish-fallback.marko template into w.
func NullishFallback(w *runtime.Writer, input NullishFallbackInput) {
	w.BeginTemplate()
	w.AllocScopeID()
	w.HTML("<h1>")
	w.HTML(runtime.Escape(runtime.Or(input.Title, "Untitled")))
	w.HTML("</h1>")
	w.EndTemplate("nullish-fallback.marko")
}
