// Code generated by marko-go. DO NOT EDIT.
package pages

import "github.com/svallory/go-marko/runtime"

type StaticInput struct{}

// Static renders the static.marko template into w.
func Static(w *runtime.Writer, input StaticInput) {
	w.HTML("<div class=static>Hello, static world.</div>")
}
