// Code generated by marko-go. DO NOT EDIT.
package pages

import (
	"github.com/svallory/go-marko/runtime"
	"goldenfix/marko_modules/tiny_tags"
)

type VendorTagInput struct{}

// VendorTag renders the vendor-tag.marko template into w.
func VendorTag(w *runtime.Writer, input VendorTagInput) {
	w.HTML("<div>")
	tiny_tags.TinyBadge(w, tiny_tags.TinyBadgeInput{
		Label: "hi",
	})
	w.HTML("</div>")
}
