// Code generated by marko-go. DO NOT EDIT.
package tiny_tags

import "github.com/svallory/go-marko/runtime"

// GeneratedByMarkoGo_v0_1 asserts this file was generated by a marko-go whose
// minor version matches the runtime package below. A build error here
// ("undefined: runtime.GeneratedByMarkoGo_v0_1") means codegen and runtime have drifted -- update whichever is
// behind so both are on the same major.minor version.
var _ = runtime.GeneratedByMarkoGo_v0_1

type TinyBadgeInput struct {
	Label string
}

// TinyBadge renders the tiny-badge.marko template into w.
func TinyBadge(w *runtime.Writer, input TinyBadgeInput) {
	w.BeginTemplate()
	w.AllocScopeID()
	w.HTML("<span class=tiny-badge>")
	w.HTML(runtime.Escape(input.Label))
	w.HTML("</span>")
	w.EndTemplate("tiny-badge.marko")
}
