// Code generated by marko-go. DO NOT EDIT.
package ui

// Globals is the request-scoped context every template can read as
// `$global.<field>`. Generated from the `Marko.Global` interface in
// global.d.ts.
//
// Provide it per request with marko.WithGlobals; rendering without it
// yields the zero value.
type Globals struct {
	Path string
}
