// Code generated by marko-go. DO NOT EDIT.
package hello

import "github.com/svallory/go-marko/runtime"

// GeneratedByMarkoGo_v0_1 asserts this file was generated by a marko-go whose
// minor version matches the runtime package below. A build error here
// ("undefined: runtime.GeneratedByMarkoGo_v0_1") means codegen and runtime have drifted -- update whichever is
// behind so both are on the same major.minor version.
var _ = runtime.GeneratedByMarkoGo_v0_1

type HelloInput struct {
	Name  string
	Items []string
}

// Hello renders the hello.marko template into w.
func Hello(w *runtime.Writer, input HelloInput) {
	w.BeginTemplate()
	w.AllocScopeID()
	w.HTML("<div><h1>Hello ")
	w.HTML(runtime.Escape(input.Name))
	w.HTML("!</h1>")
	if runtime.Truthy(len(input.Items)) {
		w.AllocScopeID()
		w.HTML("<ul>")
		runtime.ForOf(input.Items, func(item string) {
			w.AllocScopeID()
			w.HTML("<li>")
			w.HTML(runtime.Escape(item))
			w.HTML("</li>")
		})
		w.HTML("</ul>")
	}
	w.HTML("</div>")
	w.EndTemplate("hello.marko")
}
