// Code generated by marko-go. DO NOT EDIT.
package hello

import "github.com/svallory/go-marko/runtime"

type HelloInput struct {
	Name  string
	Items []string
}

// Hello renders the hello.marko template into w.
func Hello(w *runtime.Writer, input HelloInput) {
	w.HTML("<div><h1>Hello ")
	w.HTML(runtime.Escape(input.Name))
	w.HTML("!</h1>")
	if runtime.Truthy(len(input.Items)) {
		w.HTML("<ul>")
		runtime.ForOf(input.Items, func(item string) {
			w.HTML("<li>")
			w.HTML(runtime.Escape(item))
			w.HTML("</li>")
		})
		w.HTML("</ul>")
	}
	w.HTML("</div>")
}
