// Code generated by marko-go/codegen. DO NOT EDIT.
package views

import "github.com/svallory/marko-go/runtime"

// Render renders the template into w. See input.go for the Input struct
// this expects.
func Render(w *runtime.Writer, input Input) {
	w.HTML("<div><h1>Hello ")
	w.HTML(runtime.Escape(input.Name))
	w.HTML("!</h1>")
	if runtime.Truthy(len(input.Items)) {
		w.HTML("<ul>")
		runtime.ForOf(input.Items, func(item any) {
			w.HTML("<li>")
			w.HTML(runtime.Escape(item))
			w.HTML("</li>")
		})
		w.HTML("</ul>")
	}
	w.HTML("</div>")
}
