package runtime

// Codegen/runtime lockstep versioning.
//
// marko-go (the npm package under codegen/) and this runtime package are
// versioned together: a git tag vX.Y.Z releases both -- npm publish of
// marko-go, and the Go module tag github.com/svallory/go-marko@vX.Y.Z (Go
// modules read repo tags directly, so one tag covers both by construction).
// See CONTRIBUTING.md for the release procedure.
//
// The two halves are nonetheless compiled independently (`npm`/`bun install`
// vs. `go get`), so nothing stops a project from ending up with a marko-go
// CLI and a runtime package whose MINOR or MAJOR versions have drifted --
// e.g. `go get -u` bumps the runtime but the CLI wasn't reinstalled. A minor
// or major bump is allowed to change the Go API codegen emits calls against
// (new Writer methods, renamed intrinsics, a different resume wire shape),
// so that combination must fail LOUDLY, at compile time, with a message that
// tells the user what to do. A patch bump is bug fixes only and must never
// break the build.
//
// Every generated `.marko.go` file references exactly one of the constants
// below, named after the major.minor version of the marko-go that generated
// it (see codegen/src/version.mjs's versionSentinelName + emit.mjs /
// globals.mjs):
//
//	var _ = runtime.GeneratedByMarkoGo_v0_1
//
// The reference costs nothing at runtime -- it's a constant read whose value
// is discarded, so the compiler drops it entirely. What it buys: if the
// installed runtime predates the codegen that produced the file, or has
// moved past it (a later release dropped the old constant, as this file's
// convention below does on every minor bump), `go build` fails with
//
//	undefined: runtime.GeneratedByMarkoGo_v0_1
//
// which unambiguously names the required runtime version and needs no
// custom tooling to diagnose.
//
// Convention for bumping: adding a new minor version's constant is
// additive -- keep prior constants around for as long as their generated
// output is expected to still build (typically: don't remove one until the
// next major version). A major version bump may drop everything from the
// previous major and start a fresh set, since a major bump already permits
// breaking changes.
const (
	// GeneratedByMarkoGo_v0_1 is referenced by every file generated by
	// marko-go v0.x (major.minor 0.1). Do not remove while any supported
	// marko-go 0.1.x release is expected to build against this runtime.
	GeneratedByMarkoGo_v0_1 = 0
)
