// Code generated by marko-go. DO NOT EDIT.
package counter

import "github.com/svallory/go-marko/runtime"

// GeneratedByMarkoGo_v0_1 asserts this file was generated by a marko-go whose
// minor version matches the runtime package below. A build error here
// ("undefined: runtime.GeneratedByMarkoGo_v0_1") means codegen and runtime have drifted -- update whichever is
// behind so both are on the same major.minor version.
var _ = runtime.GeneratedByMarkoGo_v0_1

type CounterInput struct {
	Global float64
	User   float64
}

// Counter renders the counter.marko template into w.
func Counter(w *runtime.Writer, input CounterInput) {
	w.BeginTemplate()
	w.AllocScopeID()
	w.HTML("<html><head><meta charset=UTF-8><meta name=viewport content=\"width=device-width, initial-scale=1.0\"><title>Counts</title></head><body><h1>Counts</h1><div>Global: ")
	w.HTML(runtime.Escape(input.Global))
	w.HTML("</div><div>User: ")
	w.HTML(runtime.Escape(input.User))
	w.HTML("</div><form action=\"/\" method=POST><div><button type=submit name=global value=global>Global</button></div><div><button type=submit name=user value=user>User</button></div></form>")
	w.Trailer("</body></html>")
	w.EndTemplate("counter.marko")
}
