// Code generated by marko-go/codegen. DO NOT EDIT.
package views

import "github.com/svallory/go-marko/runtime"

// Render renders the template into w. See input.go for the Input struct
// this expects.
func Render(w *runtime.Writer, input Input) {
	w.HTML("<html><head><meta charset=UTF-8><meta name=viewport content=\"width=device-width, initial-scale=1.0\"><title>Counts</title></head><body><h1>Counts</h1><div>Global: ")
	w.HTML(runtime.Escape(input.Global))
	w.HTML("</div><div>User: ")
	w.HTML(runtime.Escape(input.User))
	w.HTML("</div><form action=\"/\" method=POST><div><button type=submit name=global value=global>Global</button></div><div><button type=submit name=user value=user>User</button></div></form>")
	w.HTML("</body></html>")
}
