// Code generated by marko-go. DO NOT EDIT.
package widgets

import "github.com/svallory/go-marko/runtime"

// GeneratedByMarkoGo_v0_1 asserts this file was generated by a marko-go whose
// minor version matches the runtime package below. A build error here
// ("undefined: runtime.GeneratedByMarkoGo_v0_1") means codegen and runtime have drifted -- update whichever is
// behind so both are on the same major.minor version.
var _ = runtime.GeneratedByMarkoGo_v0_1

type PanelInput struct {
	Attrs   map[string]any
	Content runtime.Body
}

// Panel renders the panel.marko template into w.
func Panel(w *runtime.Writer, input PanelInput) {
	w.BeginTemplate()
	scope0_id := w.AllocScopeID()
	w.HTML("<div")
	w.HTML(runtime.Attrs(runtime.A{Name: "class", Value: "panel"}, input.Attrs))
	w.HTML(">")
	if input.Content != nil {
		input.Content(w)
	}
	w.HTML("</div>")
	w.Marker(runtime.OpResume, scope0_id, "a")
	w.AddScript("lrYmeYG", scope0_id)
	w.TouchScope(scope0_id)
	w.EndTemplate("panel.marko")
}
