// Code generated by marko-go. DO NOT EDIT.
package layouts

import "github.com/svallory/go-marko/runtime"

// GeneratedByMarkoGo_v0_1 asserts this file was generated by a marko-go whose
// minor version matches the runtime package below. A build error here
// ("undefined: runtime.GeneratedByMarkoGo_v0_1") means codegen and runtime have drifted -- update whichever is
// behind so both are on the same major.minor version.
var _ = runtime.GeneratedByMarkoGo_v0_1

type PageLayoutInput struct {
	Title   string
	Head    *PageLayoutInputHead
	Content runtime.Body
}

type PageLayoutInputHead struct {
	Content runtime.Body
}

// PageLayout renders the page-layout.marko template into w.
func PageLayout(w *runtime.Writer, input PageLayoutInput) {
	w.BeginTemplate()
	w.AllocScopeID()
	w.HTML("<!DOCTYPE html><html lang=en><head><meta charset=UTF-8><title>")
	w.HTML(runtime.Escape(runtime.Or(input.Title, "goldenfix")))
	w.HTML("</title>")
	if input.Head != nil {
		w.AllocScopeID()
		if input.Head.Content != nil {
			input.Head.Content(w)
		}
	}
	w.HTML("</head><body>")
	if input.Content != nil {
		input.Content(w)
	}
	w.Trailer("</body></html>")
	w.EndTemplate("page-layout.marko")
}
