// Code generated by marko-go. DO NOT EDIT.
package tiny_tags

import "github.com/svallory/go-marko/runtime"

type TinyBadgeInput struct {
	Label string
}

// TinyBadge renders the tiny-badge.marko template into w.
func TinyBadge(w *runtime.Writer, input TinyBadgeInput) {
	w.BeginTemplate()
	w.AllocScopeID()
	w.HTML("<span class=tiny-badge>")
	w.HTML(runtime.Escape(input.Label))
	w.HTML("</span>")
	w.EndTemplate("tiny-badge.marko")
}
