// Code generated by marko-go. DO NOT EDIT.
package layouts

import "github.com/svallory/go-marko/runtime"

type PageLayoutInput struct {
	Title   string
	Head    *PageLayoutInputHead
	Content runtime.Body
}

type PageLayoutInputHead struct {
	Content runtime.Body
}

// PageLayout renders the page-layout.marko template into w.
func PageLayout(w *runtime.Writer, input PageLayoutInput) {
	w.HTML("<!DOCTYPE html><html lang=en><head><meta charset=UTF-8><title>")
	w.HTML(runtime.Escape(runtime.Or(input.Title, "goldenfix")))
	w.HTML("</title>")
	if input.Head != nil {
		if input.Head.Content != nil {
			input.Head.Content(w)
		}
	}
	w.HTML("</head><body>")
	if input.Content != nil {
		input.Content(w)
	}
	w.HTML("</body></html>")
}
