// Code generated by marko-go. DO NOT EDIT.
package nested

import "github.com/svallory/go-marko/runtime"

type InnerBadgeInput struct {
	Text string
}

// InnerBadge renders the inner-badge.marko template into w.
func InnerBadge(w *runtime.Writer, input InnerBadgeInput) {
	w.HTML("<span class=inner-badge>")
	w.HTML(runtime.Escape(input.Text))
	w.HTML("</span>")
}
