// Code generated by marko-go. DO NOT EDIT.
package nested

import "github.com/svallory/go-marko/runtime"

// GeneratedByMarkoGo_v0_1 asserts this file was generated by a marko-go whose
// minor version matches the runtime package below. A build error here
// ("undefined: runtime.GeneratedByMarkoGo_v0_1") means codegen and runtime have drifted -- update whichever is
// behind so both are on the same major.minor version.
var _ = runtime.GeneratedByMarkoGo_v0_1

type InnerBadgeInput struct {
	Text string
}

// InnerBadge renders the inner-badge.marko template into w.
func InnerBadge(w *runtime.Writer, input InnerBadgeInput) {
	w.BeginTemplate()
	w.AllocScopeID()
	w.HTML("<span class=inner-badge>")
	w.HTML(runtime.Escape(input.Text))
	w.HTML("</span>")
	w.EndTemplate("inner-badge.marko")
}
