// Code generated by marko-go. DO NOT EDIT.
package pages

import (
	"github.com/svallory/go-marko/runtime"
	"goldenfix/ui/tags/widgets"
)

// GeneratedByMarkoGo_v0_1 asserts this file was generated by a marko-go whose
// minor version matches the runtime package below. A build error here
// ("undefined: runtime.GeneratedByMarkoGo_v0_1") means codegen and runtime have drifted -- update whichever is
// behind so both are on the same major.minor version.
var _ = runtime.GeneratedByMarkoGo_v0_1

type AttrsSpreadInput struct{}

// AttrsSpread renders the attrs-spread.marko template into w.
func AttrsSpread(w *runtime.Writer, input AttrsSpreadInput) {
	w.BeginTemplate()
	w.AllocScopeID()
	widgets.Panel(w, widgets.PanelInput{
		Attrs: map[string]any{
			"id":        "main-panel",
			"data-role": "container",
		},
		Content: func(w *runtime.Writer) {
			w.AllocScopeID()
			w.HTML("spread body")
		},
	})
	w.EndTemplate("attrs-spread.marko")
}
