// Code generated by marko-go. DO NOT EDIT.
package pages

import (
	"github.com/svallory/go-marko/runtime"
	"goldenfix/ui/tags/widgets/nested"
)

// GeneratedByMarkoGo_v0_1 asserts this file was generated by a marko-go whose
// minor version matches the runtime package below. A build error here
// ("undefined: runtime.GeneratedByMarkoGo_v0_1") means codegen and runtime have drifted -- update whichever is
// behind so both are on the same major.minor version.
var _ = runtime.GeneratedByMarkoGo_v0_1

type CrossDirInput struct{}

// CrossDir renders the cross-dir.marko template into w.
func CrossDir(w *runtime.Writer, input CrossDirInput) {
	w.BeginTemplate()
	w.AllocScopeID()
	w.HTML("<div>")
	nested.InnerBadge(w, nested.InnerBadgeInput{
		Text: "deep",
	})
	w.HTML("</div>")
	w.EndTemplate("cross-dir.marko")
}
