// Code generated by marko-go. DO NOT EDIT.
package pages

import (
	"github.com/svallory/go-marko/runtime"
	"goldenfix/ui"
)

// GeneratedByMarkoGo_v0_1 asserts this file was generated by a marko-go whose
// minor version matches the runtime package below. A build error here
// ("undefined: runtime.GeneratedByMarkoGo_v0_1") means codegen and runtime have drifted -- update whichever is
// behind so both are on the same major.minor version.
var _ = runtime.GeneratedByMarkoGo_v0_1

type GlobalReadInput struct{}

// GlobalRead renders the global-read.marko template into w.
func GlobalRead(w *runtime.Writer, input GlobalReadInput) {
	w.BeginTemplate()
	w.AllocScopeID()
	markoGlobal, _ := w.Globals().(ui.Globals)
	w.HTML("<div>Current path: ")
	w.HTML(runtime.Escape(markoGlobal.Path))
	w.HTML("</div>")
	w.EndTemplate("global-read.marko")
}
