// Code generated by marko-go. DO NOT EDIT.
package pages

import "github.com/svallory/go-marko/runtime"

// GeneratedByMarkoGo_v0_1 asserts this file was generated by a marko-go whose
// minor version matches the runtime package below. A build error here
// ("undefined: runtime.GeneratedByMarkoGo_v0_1") means codegen and runtime have drifted -- update whichever is
// behind so both are on the same major.minor version.
var _ = runtime.GeneratedByMarkoGo_v0_1

type HtmlScriptInput struct{}

// HtmlScript renders the html-script.marko template into w.
func HtmlScript(w *runtime.Writer, input HtmlScriptInput) {
	w.BeginTemplate()
	w.AllocScopeID()
	w.HTML("<div><script")
	w.HTML(" src=/assets/js/app.js defer></script></div>")
	w.EndTemplate("html-script.marko")
}
