// Code generated by marko-go. DO NOT EDIT.
package pages

import "github.com/svallory/go-marko/runtime"

// GeneratedByMarkoGo_v0_1 asserts this file was generated by a marko-go whose
// minor version matches the runtime package below. A build error here
// ("undefined: runtime.GeneratedByMarkoGo_v0_1") means codegen and runtime have drifted -- update whichever is
// behind so both are on the same major.minor version.
var _ = runtime.GeneratedByMarkoGo_v0_1

var moduleConstVariants = map[string]string{
	"default": "btn-default",
	"outline": "btn-outline",
}

type ModuleConstInput struct {
	Variant string
}

// ModuleConst renders the module-const.marko template into w.
func ModuleConst(w *runtime.Writer, input ModuleConstInput) {
	w.BeginTemplate()
	w.AllocScopeID()
	w.HTML("<button")
	w.HTML(runtime.AttrClass(moduleConstVariants[input.Variant]))
	w.HTML(">Click</button>")
	w.EndTemplate("module-const.marko")
}
