// Code generated by marko-go. DO NOT EDIT.
package pages

import "github.com/svallory/go-marko/runtime"

// GeneratedByMarkoGo_v0_1 asserts this file was generated by a marko-go whose
// minor version matches the runtime package below. A build error here
// ("undefined: runtime.GeneratedByMarkoGo_v0_1") means codegen and runtime have drifted -- update whichever is
// behind so both are on the same major.minor version.
var _ = runtime.GeneratedByMarkoGo_v0_1

type NullishFallbackInput struct {
	Title string
}

// NullishFallback renders the nullish-fallback.marko template into w.
func NullishFallback(w *runtime.Writer, input NullishFallbackInput) {
	w.BeginTemplate()
	w.AllocScopeID()
	w.HTML("<h1>")
	w.HTML(runtime.Escape(runtime.Or(input.Title, "Untitled")))
	w.HTML("</h1>")
	w.EndTemplate("nullish-fallback.marko")
}
