// Code generated by marko-go. DO NOT EDIT.
package pages

import "github.com/svallory/go-marko/runtime"

// GeneratedByMarkoGo_v0_1 asserts this file was generated by a marko-go whose
// minor version matches the runtime package below. A build error here
// ("undefined: runtime.GeneratedByMarkoGo_v0_1") means codegen and runtime have drifted -- update whichever is
// behind so both are on the same major.minor version.
var _ = runtime.GeneratedByMarkoGo_v0_1

type StaticInput struct{}

// Static renders the static.marko template into w.
func Static(w *runtime.Writer, input StaticInput) {
	w.BeginTemplate()
	w.AllocScopeID()
	w.HTML("<div class=static>Hello, static world.</div>")
	w.EndTemplate("static.marko")
}
