// Code generated by marko-go. DO NOT EDIT.
package pages

import (
	"github.com/svallory/go-marko/runtime"
	"goldenfix/marko_modules/tiny_tags"
)

// GeneratedByMarkoGo_v0_1 asserts this file was generated by a marko-go whose
// minor version matches the runtime package below. A build error here
// ("undefined: runtime.GeneratedByMarkoGo_v0_1") means codegen and runtime have drifted -- update whichever is
// behind so both are on the same major.minor version.
var _ = runtime.GeneratedByMarkoGo_v0_1

type VendorTagInput struct{}

// VendorTag renders the vendor-tag.marko template into w.
func VendorTag(w *runtime.Writer, input VendorTagInput) {
	w.BeginTemplate()
	w.AllocScopeID()
	w.HTML("<div>")
	tiny_tags.TinyBadge(w, tiny_tags.TinyBadgeInput{
		Label: "hi",
	})
	w.HTML("</div>")
	w.EndTemplate("vendor-tag.marko")
}
