import { afterEach, describe, expect, test } from "bun:test";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import {
  findGlobalDeclarations,
  parseGlobalInterface,
  findGlobals,
  renderGlobalsFile,
} from "../src/globals.mjs";
import { generateProject } from "../src/project.mjs";
import { UnsupportedError } from "../src/errors.mjs";

/**
 * FR10 -- generating `ui.Globals` from the project's `Marko.Global`
 * augmentation, and wiring `$global` reads to it.
 */

const dirs = [];

/**
 * Lay out a throwaway project: go.mod at the root, everything else under
 * ui/. Returns both paths since generateProject takes the ui dir but import
 * paths are derived from the module root.
 */
function fixture(files) {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "marko-go-globals-"));
  dirs.push(root);
  fs.writeFileSync(path.join(root, "go.mod"), "module myapp\n\ngo 1.24\n");
  const ui = path.join(root, "ui");
  for (const [rel, source] of Object.entries(files)) {
    const full = path.join(ui, rel);
    fs.mkdirSync(path.dirname(full), { recursive: true });
    fs.writeFileSync(full, source);
  }
  return { root, ui };
}

afterEach(() => {
  let d;
  while ((d = dirs.pop())) fs.rmSync(d, { recursive: true, force: true });
});

const GLOBAL_DTS = `declare global {
  namespace Marko {
    interface Global {
      path: string;
    }
  }
}
export {};
`;

describe("parseGlobalInterface", () => {
  test("reads the interface out of declare global / namespace Marko nesting", () => {
    expect(parseGlobalInterface(GLOBAL_DTS)).toEqual([
      { jsName: "path", name: "Path", goType: "string", optional: false },
    ]);
  });

  test("uses the same TS->Go mapping as interface Input", () => {
    const fields = parseGlobalInterface(`declare global {
      namespace Marko {
        interface Global {
          path: string;
          count: number;
          debug?: boolean;
          tags: string[];
          mode: "light" | "dark";
        }
      }
    }`);
    expect(fields.map((f) => [f.name, f.goType, f.optional])).toEqual([
      ["Path", "string", false],
      ["Count", "float64", false],
      ["Debug", "bool", true],
      ["Tags", "[]string", false],
      ["Mode", "string", false],
    ]);
  });

  test("a kebab key still goes through the Go field-name convention", () => {
    const fields = parseGlobalInterface(`declare global {
      namespace Marko { interface Global { "request-id": string } }
    }`);
    expect(fields[0].name).toBe("RequestId");
  });

  test("a .d.ts with no Marko.Global is an error, not an empty struct", () => {
    expect(() => parseGlobalInterface(`export {};`, "x.d.ts")).toThrow(UnsupportedError);
  });
});

describe("findGlobalDeclarations", () => {
  test("finds the declaring .d.ts and ignores unrelated ones", () => {
    const { ui } = fixture({
      "global.d.ts": GLOBAL_DTS,
      "other.d.ts": `declare module "x" { const y: string; }`,
    });
    expect(findGlobalDeclarations(ui)).toEqual([path.join(ui, "global.d.ts")]);
  });

  test("the file name does not matter -- the declaration does", () => {
    const { ui } = fixture({ "types/marko-env.d.ts": GLOBAL_DTS });
    expect(findGlobalDeclarations(ui)).toEqual([
      path.join(ui, "types", "marko-env.d.ts"),
    ]);
  });

  test("a project with no declaration returns nothing", () => {
    const { ui } = fixture({ "hello.marko": "<div>hi</div>\n" });
    expect(findGlobalDeclarations(ui)).toEqual([]);
  });
});

describe("renderGlobalsFile", () => {
  test("emits a Globals struct in the .d.ts's own directory package", () => {
    const { ui } = fixture({ "global.d.ts": GLOBAL_DTS });
    const globals = findGlobals(ui, { modulePath: "myapp", moduleRoot: path.dirname(ui) });
    expect(globals.pkgName).toBe("ui");
    expect(globals.goImportPath).toBe("myapp/ui");
    expect(globals.outPath).toBe(path.join(ui, "globals.marko.go"));

    const code = renderGlobalsFile(globals);
    expect(code).toStartWith("// Code generated by marko-go. DO NOT EDIT.\n");
    expect(code).toContain("\npackage ui\n");
    expect(code).toContain("type Globals struct {\n\tPath string\n}");
    // No runtime types among the fields, but the file still imports runtime
    // for the codegen/runtime version sentinel (see version.mjs) -- every
    // generated file references it, unconditionally.
    expect(code).toContain('import "github.com/svallory/go-marko/runtime"');
    expect(code).toContain("var _ = runtime.GeneratedByMarkoGo_v0_1");
  });
});

describe("generateProject with globals", () => {
  test("writes globals.marko.go next to the .d.ts", async () => {
    const { ui } = fixture({
      "global.d.ts": GLOBAL_DTS,
      "hello.marko": "<div>hi</div>\n",
    });
    const { goFiles: results } = await generateProject(ui);
    const rels = results.map((r) => path.relative(ui, r.outPath)).sort();
    expect(rels).toEqual(["globals.marko.go", "hello.marko.go"]);
    expect(fs.readFileSync(path.join(ui, "globals.marko.go"), "utf8")).toContain(
      "type Globals struct {\n\tPath string\n}",
    );
  });

  test("a $global read imports the globals package and reads a typed field", async () => {
    const { ui } = fixture({
      "global.d.ts": GLOBAL_DTS,
      // Read $global into a text interpolation: a `class=(cond && "lit")`
      // on a NATIVE element is constant-folded by the compiler into a
      // ternary, which is a separate (pre-existing) unsupported shape.
      "pages/home.marko": "<p>${$global.path}</p>\n",
    });
    const { goFiles: results } = await generateProject(ui);
    const code = results.find((r) => r.outPath.endsWith("home.marko.go")).code;
    expect(code).toContain(`\t"myapp/ui"\n`);
    expect(code).toContain("markoGlobal, _ := w.Globals().(ui.Globals)");
    expect(code).toContain("runtime.Escape(markoGlobal.Path)");
  });

  test("a template in the SAME package as Globals needs no import", async () => {
    const { ui } = fixture({
      "global.d.ts": GLOBAL_DTS,
      "home.marko": "<p>${$global.path}</p>\n",
    });
    const { goFiles: results } = await generateProject(ui);
    const code = results.find((r) => r.outPath.endsWith("home.marko.go")).code;
    expect(code).toContain("markoGlobal, _ := w.Globals().(Globals)");
    expect(code).not.toContain(`"myapp/ui"`);
  });

  test("no .d.ts means no globals file at all", async () => {
    const { ui } = fixture({ "hello.marko": "<div>hi</div>\n" });
    const { goFiles: results } = await generateProject(ui);
    expect(results.map((r) => path.relative(ui, r.outPath))).toEqual([
      "hello.marko.go",
    ]);
    expect(fs.existsSync(path.join(ui, "globals.marko.go"))).toBe(false);
  });

  test("using $global with no declaration fails, naming global.d.ts", async () => {
    const { ui } = fixture({
      "home.marko": "<p>${$global.path}</p>\n",
    });
    const { diagnostics: errors } = await generateProject(ui, { bestEffort: true });
    expect(errors).toHaveLength(1);
    expect(errors[0].error.message).toMatch(/global\.d\.ts/);
  });

  test("two competing Marko.Global declarations are rejected", async () => {
    const { ui } = fixture({
      "global.d.ts": GLOBAL_DTS,
      "other/also-global.d.ts": GLOBAL_DTS,
    });
    await expect(generateProject(ui)).rejects.toThrow(/single definition/);
  });
});
