import { afterAll, beforeAll, describe, expect, test } from "bun:test";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { generateProject, findGoModule, findMarkoFiles } from "../src/project.mjs";
import { UnsupportedError } from "../src/errors.mjs";

/**
 * End-to-end: run `generate` over the quickstart fixture's ui/ tree and
 * assert the emitted Go. The fixture is copied into a temp dir first so the
 * real one stays pristine and a failing run leaves nothing behind.
 */
const FIXTURE =
  "/private/tmp/claude-501/-Users-svallory-work-go-marko/6b33a62a-f0c0-4f0a-af15-a7bea5f57259/scratchpad/qsfixture";

let root; // temp copy
let uiDir;
let files; // outPath -> generated Go source

const EXPECTED = [
  ["pages/counter.marko.go", "pages", "Counter"],
  ["pages/landing.marko.go", "pages", "Landing"],
  ["tags/elements/ui-button.marko.go", "elements", "UiButton"],
  ["tags/icons/icon-book.marko.go", "icons", "IconBook"],
  ["tags/icons/icon-eclipse.marko.go", "icons", "IconEclipse"],
  ["tags/icons/icon-git-branch.marko.go", "icons", "IconGitBranch"],
  ["tags/icons/icon-toggle-left.marko.go", "icons", "IconToggleLeft"],
  ["tags/layouts/page-layout.marko.go", "layouts", "PageLayout"],
  ["tags/modules/navbar.marko.go", "modules", "Navbar"],
  ["tags/modules/theme-switcher.marko.go", "modules", "ThemeSwitcher"],
];

beforeAll(async () => {
  root = fs.mkdtempSync(path.join(os.tmpdir(), "marko-go-gen-"));
  fs.cpSync(path.join(FIXTURE, "ui"), path.join(root, "ui"), { recursive: true });
  // Only the module directive matters for import-path derivation.
  fs.writeFileSync(path.join(root, "go.mod"), "module myapp\n\ngo 1.24\n");
  uiDir = path.join(root, "ui");

  const { goFiles } = await generateProject(uiDir);
  files = new Map(goFiles.map((r) => [path.relative(uiDir, r.outPath), r.code]));
});

afterAll(() => {
  if (root) fs.rmSync(root, { recursive: true, force: true });
});

function src(rel) {
  const code = files.get(rel);
  if (code === undefined) {
    throw new Error(`no generated file ${rel}; got ${[...files.keys()].join(", ")}`);
  }
  return code;
}

describe("generate over the quickstart fixture", () => {
  test("emits one .marko.go next to each of the 10 templates, plus globals", () => {
    // globals.marko.go is not a template -- it's the ui.Globals struct
    // generated from ui/global.d.ts (FR10), emitted next to the .d.ts.
    expect([...files.keys()].sort()).toEqual(
      [...EXPECTED.map(([rel]) => rel), "globals.marko.go"].sort(),
    );
    for (const [rel] of EXPECTED) {
      expect(fs.existsSync(path.join(uiDir, rel))).toBe(true);
    }
    expect(fs.existsSync(path.join(uiDir, "globals.marko.go"))).toBe(true);
  });

  test.each(EXPECTED)("%s declares package %s and func %s", (rel, pkg, fn) => {
    const code = src(rel);
    expect(code).toStartWith("// Code generated by marko-go. DO NOT EDIT.\n");
    expect(code).toContain(`\npackage ${pkg}\n`);
    expect(code).toContain(`func ${fn}(w *runtime.Writer, input ${fn}Input) {`);
    expect(code).toMatch(new RegExp(`type ${fn}Input struct`));
  });

  test("every generated file is tab-indented and ends with a newline", () => {
    for (const code of files.values()) {
      expect(code).toEndWith("\n");
      const badIndent = code
        .split("\n")
        .filter((l) => /^ +\S/.test(l) && !l.trimStart().startsWith("//"));
      expect(badIndent).toEqual([]);
    }
  });

  test("landing composes page-layout via a struct literal and a Content closure", () => {
    const code = src("pages/landing.marko.go");
    expect(code).toContain('\t"myapp/ui/tags/layouts"\n');
    expect(code).toContain("layouts.PageLayout(w, layouts.PageLayoutInput{");
    // `Content:` opens a multi-line value, so gofmt does NOT align `Title:`
    // with it -- the run is broken. (Verified against real gofmt.)
    expect(code).toContain('Title: "go-marko Quickstart",');
    expect(code).toContain("Content: func(w *runtime.Writer) {");
    // Nested composition: two buttons, each with an icon inside its body.
    expect(code).toContain("elements.UiButton(w, elements.UiButtonInput{");
    expect(code).toContain("icons.IconBook(w, icons.IconBookInput{");
    expect(code).toContain("icons.IconGitBranch(w, icons.IconGitBranchInput{");
    expect(code).toContain('Href:    "https://markojs.com/docs",');
  });

  test("landing's Input is an empty struct (the .marko declares no fields)", () => {
    expect(src("pages/landing.marko.go")).toContain("type LandingInput struct{}");
  });

  test("ui-button uses runtime.Attrs, runtime.Or and module-level consts", () => {
    const code = src("tags/elements/ui-button.marko.go");
    expect(code).toContain("runtime.Attrs(");
    expect(code).toContain('runtime.A{Name: "href", Value: input.Href}');
    expect(code).toContain('runtime.A{Name: "class", Value: classes}');
    // `...input.attrs` spread becomes a bare map item for runtime.Attrs.
    expect(code).toContain(", input.Attrs))");
    expect(code).toContain('runtime.Or(input.Variant, "default")');
    expect(code).toContain('runtime.Or(input.Type, "button")');
    // static consts are template-name-prefixed to avoid same-package clashes
    expect(code).toContain("var uiButtonBase = ");
    expect(code).toContain("var uiButtonVariants = map[string]string{");
    expect(code).toContain("var uiButtonSizes = map[string]string{");
    expect(code).toContain("uiButtonVariants[runtime.Or(input.Variant, \"default\")]");
    // both <if> branches survive, each rendering the body
    expect(code).toContain("if runtime.Truthy(input.Href) {");
    expect(code).toContain("} else {");
    expect(code).toContain("if input.Content != nil {");
  });

  test("ui-button's Input struct maps every declared TS field", () => {
    const code = src("tags/elements/ui-button.marko.go");
    expect(code).toContain(
      [
        "type UiButtonInput struct {",
        "\tVariant string",
        "\tSize    string",
        "\tHref    string",
        "\tTarget  string",
        "\tType    string",
        "\tClass   string",
        "\tAttrs   map[string]any",
        "\tContent runtime.Body",
        "}",
      ].join("\n"),
    );
  });

  test("page-layout keeps the theme.js script tag and drops _attr_nonce", () => {
    const code = src("tags/layouts/page-layout.marko.go");
    expect(code).toContain("src=/assets/js/theme.js defer></script>");
    expect(code).not.toContain("nonce");
    expect(code).not.toContain("_attr_nonce");
    // The compiler splits the literal at the (dropped) nonce interpolation.
    expect(code).toContain('w.HTML("<link href=/assets/css/output.css rel=stylesheet><script")');
    // `_trailers("</body></html>")` carries real deferred markup.
    expect(code).toContain('w.HTML("</body></html>")');
    // title uses ?? and goes through the escaper
    expect(code).toContain('w.HTML(runtime.Escape(runtime.Or(input.Title, "go-marko App")))');
    // `<${input.content}/>` -> nil-guarded body call
    expect(code).toContain("if input.Content != nil {\n\t\tinput.Content(w)\n\t}");
    expect(code).toContain("modules.Navbar(w, modules.NavbarInput{})");
  });

  test("theme-switcher passes attrs as a map[string]any and a body closure", () => {
    const code = src("tags/modules/theme-switcher.marko.go");
    expect(code).toContain("Attrs: map[string]any{");
    expect(code).toContain('"data-theme-switcher": "true",');
    expect(code).toContain("Content: func(w *runtime.Writer) {");
    expect(code).toContain("icons.IconEclipse(w, icons.IconEclipseInput{");
    // theme-switcher.marko has no client <script>; nothing resume-related leaks
    expect(code).not.toContain("_set_serialize_reason");
    expect(code).not.toContain("_peek_scope_id");
  });

  test("icons use runtime.AttrClass for their optional class attribute", () => {
    for (const rel of EXPECTED.filter(([r]) => r.includes("/icons/")).map(([r]) => r)) {
      expect(src(rel)).toContain("w.HTML(runtime.AttrClass(input.Class))");
      expect(src(rel)).toContain("type Icon");
    }
  });

  test("imports are only listed when actually used", () => {
    // A leaf icon composes nothing, so runtime is its only import.
    expect(src("tags/icons/icon-book.marko.go")).toContain(
      'import "github.com/svallory/go-marko/runtime"',
    );
    expect(src("tags/icons/icon-book.marko.go")).not.toContain("import (");
    // navbar pulls in icons (cross-dir) but calls theme-switcher unqualified
    // because it lives in the same directory / Go package.
    const navbar = src("tags/modules/navbar.marko.go");
    expect(navbar).toContain('\t"myapp/ui/tags/icons"\n');
    expect(navbar).toContain("ThemeSwitcher(w, ThemeSwitcherInput{})");
    expect(navbar).not.toContain('"myapp/ui/tags/modules"');
  });

  test("generating twice is byte-identical (deterministic output)", async () => {
    const { goFiles: again } = await generateProject(uiDir, { write: false });
    for (const r of again) {
      expect(r.code).toBe(files.get(path.relative(uiDir, r.outPath)));
    }
  });
});

describe("project plumbing", () => {
  test("findMarkoFiles walks recursively and sorts", () => {
    const found = findMarkoFiles(uiDir).map((f) => path.relative(uiDir, f));
    expect(found).toHaveLength(10);
    expect(found).toEqual([...found].sort());
  });

  test("findGoModule walks up to the nearest go.mod", () => {
    const mod = findGoModule(path.join(uiDir, "tags", "icons"));
    expect(mod.modulePath).toBe("myapp");
    expect(fs.realpathSync(mod.moduleRoot)).toBe(fs.realpathSync(root));
  });

  test("a tree with no go.mod above it fails fast", async () => {
    const orphan = fs.mkdtempSync(path.join(os.tmpdir(), "marko-go-orphan-"));
    try {
      await expect(generateProject(orphan)).rejects.toThrow(UnsupportedError);
      await expect(generateProject(orphan)).rejects.toThrow(/no go\.mod found/);
    } finally {
      fs.rmSync(orphan, { recursive: true, force: true });
    }
  });

  test("generating a non-directory fails fast", async () => {
    await expect(generateProject(path.join(uiDir, "pages", "landing.marko"))).rejects.toThrow(
      /not a directory/,
    );
  });
});

/**
 * FR10 + FR11 over the real fixture: the quickstart declares
 * `Marko.Global { path }` in ui/global.d.ts, navbar reads `$global.path`,
 * page-layout declares an optional `<@head>` section, and counter passes one.
 */
describe("$global and attr tags over the fixture", () => {
  test("ui/global.d.ts generates the ui.Globals struct", () => {
    const code = src("globals.marko.go");
    expect(code).toStartWith("// Code generated by marko-go. DO NOT EDIT.\n");
    expect(code).toContain("\npackage ui\n");
    expect(code).toContain("type Globals struct {\n\tPath string\n}");
  });

  test("navbar reads $global off the Writer and imports the ui package", () => {
    const code = src("tags/modules/navbar.marko.go");
    expect(code).toContain(`\t"myapp/ui"\n`);
    expect(code).toContain("markoGlobal, _ := w.Globals().(ui.Globals)");
    // The active-link test: a typed string comparison, only possible
    // because Path is known to be a string.
    expect(code).toContain(`markoGlobal.Path == "/counter"`);
  });

  test("page-layout declares the <@head> section as a POINTER plus its struct", () => {
    const code = src("tags/layouts/page-layout.marko.go");
    expect(code).toContain("Head    *PageLayoutInputHead");
    expect(code).toContain("type PageLayoutInputHead struct {\n\tContent runtime.Body\n}");
  });

  test("page-layout tests the optional section with != nil, not runtime.Truthy", () => {
    const code = src("tags/layouts/page-layout.marko.go");
    expect(code).toContain("if input.Head != nil {");
    expect(code).not.toContain("runtime.Truthy(input.Head)");
    expect(code).toContain("input.Head.Content(w)");
  });

  test("counter passes <@head> as a pointer to the callee's section struct", () => {
    const code = src("pages/counter.marko.go");
    expect(code).toContain("Head: &layouts.PageLayoutInputHead{");
    expect(code).toContain("<meta name=description");
  });

  test("landing passes no <@head>, so the field stays nil", () => {
    const code = src("pages/landing.marko.go");
    expect(code).not.toContain("PageLayoutInputHead");
  });
});
